Discovery starting.
Discovery completed in 7 seconds, 592 milliseconds.
Run starting. Expected test count is: 4
ChatBotServiceTest:
SearchDictFlowTest:
- Search dictionary conversation (3 seconds, 849 milliseconds)
AnalyticsTest:
xed.api_service.service.AnalyticsTest *** ABORTED *** (1 millisecond)
  java.lang.RuntimeException: Unable to load a Suite class that was discovered in the runpath: xed.api_service.service.AnalyticsTest
  at org.scalatest.tools.DiscoverySuite$.getSuiteInstance(DiscoverySuite.scala:81)
  at org.scalatest.tools.DiscoverySuite$$anonfun$1.apply(DiscoverySuite.scala:38)
  at org.scalatest.tools.DiscoverySuite$$anonfun$1.apply(DiscoverySuite.scala:37)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
  at scala.collection.Iterator$class.foreach(Iterator.scala:891)
  at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
  at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
  at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
  at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
  at scala.collection.AbstractTraversable.map(Traversable.scala:104)
  at org.scalatest.tools.DiscoverySuite.<init>(DiscoverySuite.scala:37)
  at org.scalatest.tools.Runner$.genDiscoSuites$1(Runner.scala:1165)
  at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:1250)
  at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1011)
  at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1010)
  at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1506)
  at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:1010)
  at org.scalatest.tools.Runner$.main(Runner.scala:827)
  at org.scalatest.tools.Runner.main(Runner.scala)
  Cause: com.google.inject.CreationException: Unable to create injector, see the following errors:

1) No implementation for xed.chatbot.repository.CourseLearningRepository was bound.
  at xed.api_service.module.XedApiModule$.providesCourseService(XedModule.scala:362)

1 error
  at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:466)
  at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:155)
  at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107)
  at com.google.inject.Guice.createInjector(Guice.java:96)
  at com.google.inject.Guice.createInjector(Guice.java:73)
  at com.google.inject.Guice.createInjector(Guice.java:62)
  at xed.api_service.service.AnalyticsTest.injector(AnalyticsTest.scala:33)
  at xed.api_service.service.AnalyticsTest.<init>(AnalyticsTest.scala:10)
  at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
  at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
  at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
  at java.lang.Class.newInstance(Class.java:442)
  at org.scalatest.tools.DiscoverySuite$.getSuiteInstance(DiscoverySuite.scala:66)
  at org.scalatest.tools.DiscoverySuite$$anonfun$1.apply(DiscoverySuite.scala:38)
  at org.scalatest.tools.DiscoverySuite$$anonfun$1.apply(DiscoverySuite.scala:37)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
  at scala.collection.Iterator$class.foreach(Iterator.scala:891)
  at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
  at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
  at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
  at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
  at scala.collection.AbstractTraversable.map(Traversable.scala:104)
  at org.scalatest.tools.DiscoverySuite.<init>(DiscoverySuite.scala:37)
  at org.scalatest.tools.Runner$.genDiscoSuites$1(Runner.scala:1165)
  at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:1250)
  at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1011)
  at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1010)
  at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1506)
  at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:1010)
  at org.scalatest.tools.Runner$.main(Runner.scala:827)
  at org.scalatest.tools.Runner.main(Runner.scala)
AuthenServiceTest:
xed.api_service.service.AuthenServiceTest *** ABORTED *** (0 milliseconds)
  java.lang.RuntimeException: Unable to load a Suite class that was discovered in the runpath: xed.api_service.service.AuthenServiceTest
  at org.scalatest.tools.DiscoverySuite$.getSuiteInstance(DiscoverySuite.scala:81)
  at org.scalatest.tools.DiscoverySuite$$anonfun$1.apply(DiscoverySuite.scala:38)
  at org.scalatest.tools.DiscoverySuite$$anonfun$1.apply(DiscoverySuite.scala:37)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
  at scala.collection.Iterator$class.foreach(Iterator.scala:891)
  at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
  at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
  at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
  at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
  at scala.collection.AbstractTraversable.map(Traversable.scala:104)
  at org.scalatest.tools.DiscoverySuite.<init>(DiscoverySuite.scala:37)
  at org.scalatest.tools.Runner$.genDiscoSuites$1(Runner.scala:1165)
  at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:1250)
  at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1011)
  at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1010)
  at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1506)
  at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:1010)
  at org.scalatest.tools.Runner$.main(Runner.scala:827)
  at org.scalatest.tools.Runner.main(Runner.scala)
  Cause: com.google.inject.CreationException: Unable to create injector, see the following errors:

1) No implementation for xed.chatbot.repository.CourseLearningRepository was bound.
  at xed.api_service.module.XedApiModule$.providesCourseService(XedModule.scala:362)

1 error
  at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:466)
  at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:155)
  at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107)
  at com.google.inject.Guice.createInjector(Guice.java:96)
  at com.google.inject.Guice.createInjector(Guice.java:73)
  at com.google.inject.Guice.createInjector(Guice.java:62)
  at xed.api_service.service.AuthenServiceTest.injector(AuthenServiceTest.scala:11)
  at xed.api_service.service.AuthenServiceTest.<init>(AuthenServiceTest.scala:13)
  at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
  at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
  at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
  at java.lang.Class.newInstance(Class.java:442)
  at org.scalatest.tools.DiscoverySuite$.getSuiteInstance(DiscoverySuite.scala:66)
  at org.scalatest.tools.DiscoverySuite$$anonfun$1.apply(DiscoverySuite.scala:38)
  at org.scalatest.tools.DiscoverySuite$$anonfun$1.apply(DiscoverySuite.scala:37)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
  at scala.collection.Iterator$class.foreach(Iterator.scala:891)
  at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
  at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
  at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
  at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
  at scala.collection.AbstractTraversable.map(Traversable.scala:104)
  at org.scalatest.tools.DiscoverySuite.<init>(DiscoverySuite.scala:37)
  at org.scalatest.tools.Runner$.genDiscoSuites$1(Runner.scala:1165)
  at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:1250)
  at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1011)
  at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1010)
  at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1506)
  at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:1010)
  at org.scalatest.tools.Runner$.main(Runner.scala:827)
  at org.scalatest.tools.Runner.main(Runner.scala)
ChallengeFlowTest:
- Create Challenge Phrasal Verb A *** FAILED *** (13 milliseconds)
  org.nutz.ssdb4j.spi.SSDBException: org.nutz.ssdb4j.spi.SSDBException: java.net.ConnectException: Connection refused (Connection refused)
  at org.nutz.ssdb4j.pool.PoolSSDBStream.req(PoolSSDBStream.java:34)
  at org.nutz.ssdb4j.impl.SimpleClient.req(SimpleClient.java:49)
  at org.nutz.ssdb4j.impl.SimpleClient.qclear(SimpleClient.java:258)
  at education.x.commons.SsdbList$$anonfun$clear$1.apply$mcZ$sp(SsdbList.scala:63)
  at education.x.commons.SsdbList$$anonfun$clear$1.apply(SsdbList.scala:63)
  at education.x.commons.SsdbList$$anonfun$clear$1.apply(SsdbList.scala:63)
  at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
  at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
  at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
  at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
  at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
  at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
  at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
  Cause: org.nutz.ssdb4j.spi.SSDBException: java.net.ConnectException: Connection refused (Connection refused)
  at org.nutz.ssdb4j.impl.SocketSSDBStream.beforeExec(SocketSSDBStream.java:48)
  at org.nutz.ssdb4j.impl.AbstractIoSSDBStream.req(AbstractIoSSDBStream.java:20)
  at org.nutz.ssdb4j.pool.PoolSSDBStream.req(PoolSSDBStream.java:24)
  at org.nutz.ssdb4j.impl.SimpleClient.req(SimpleClient.java:49)
  at org.nutz.ssdb4j.impl.SimpleClient.qclear(SimpleClient.java:258)
  at education.x.commons.SsdbList$$anonfun$clear$1.apply$mcZ$sp(SsdbList.scala:63)
  at education.x.commons.SsdbList$$anonfun$clear$1.apply(SsdbList.scala:63)
  at education.x.commons.SsdbList$$anonfun$clear$1.apply(SsdbList.scala:63)
  at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
  at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
  at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
  at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
  at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
  at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
  at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
  Cause: java.net.ConnectException: Connection refused (Connection refused)
  at java.net.PlainSocketImpl.socketConnect(Native Method)
  at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
  at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
  at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
  at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
  at java.net.Socket.connect(Socket.java:607)
  at org.nutz.ssdb4j.impl.SocketSSDBStream.beforeExec(SocketSSDBStream.java:37)
  at org.nutz.ssdb4j.impl.AbstractIoSSDBStream.req(AbstractIoSSDBStream.java:20)
  at org.nutz.ssdb4j.pool.PoolSSDBStream.req(PoolSSDBStream.java:24)
  at org.nutz.ssdb4j.impl.SimpleClient.req(SimpleClient.java:49)
  at org.nutz.ssdb4j.impl.SimpleClient.qclear(SimpleClient.java:258)
  at education.x.commons.SsdbList$$anonfun$clear$1.apply$mcZ$sp(SsdbList.scala:63)
  at education.x.commons.SsdbList$$anonfun$clear$1.apply(SsdbList.scala:63)
  at education.x.commons.SsdbList$$anonfun$clear$1.apply(SsdbList.scala:63)
  at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
  at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
  at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
  at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
  at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
  at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
  at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
- Join Challenge (0 milliseconds)
LearnFlowTest:
- Learn flow (1 second, 956 milliseconds)
Run completed in 14 seconds, 13 milliseconds.
Total number of tests run: 4
Suites: completed 5, aborted 2
Tests: succeeded 3, failed 1, canceled 0, ignored 0, pending 0
*** 2 SUITES ABORTED ***
*** 1 TEST FAILED ***
